package Latam.Latam.work.hub.enums;


public enum Permission {
    // ADMIN
    CREAR_USUARIO,
    ELIMINAR_USUARIO,
    APROBAR_PROVEEDOR,
    ACTIVAR_CUENTA,
    MODIFICAR_ESPACIO,
    VER_TRANSACCIONES,
    CANCELAR_RESERVA,
    GESTIONAR_REEMBOLSOS,
    VER_INFORMES,
    CONFIGURAR_SISTEMA,

    // PROVEEDOR
    CREAR_ESPACIO,
    ESTABLECER_PRECIO,
    GESTIONAR_CONTRATO,
    VER_PAGOS_RECIBIDOS,
    EMITIR_FACTURAS,
    VER_INFORMES_PROPIO,

    // CLIENTE
    BUSCAR_ESPACIOS,
    VER_DETALLES_ESPACIO,
    CREAR_RESERVA,
    CANCELAR_RESERVA_CLIENTE,
    CALIFICAR_ESPACIO,
    REALIZAR_PAGO,
    VER_HISTORIAL_PAGOS,
    DESCARGAR_FACTURA,

    // Comunes
    VER_ESPACIOS
}
